"""GitHub API access (PyGithub) and repository URL parsing."""

from __future__ import annotations

import re

from github import Auth, Github, GithubException
from pydantic import BaseModel

from ci_fix.logging_setup import get_logger

log = get_logger(__name__)

_NAME = r"[A-Za-z0-9_.-]+"
_REPO_URL_RE = re.compile(
    rf"^(?:https?://(?:www\.)?github\.com/|git@github\.com:)(?P<owner>{_NAME})/(?P<name>{_NAME})/?$"
)


class GitHubError(Exception):
    """Raised for GitHub API failures and invalid repository references."""


class RepoRef(BaseModel, frozen=True):
    owner: str
    name: str

    @property
    def full_name(self) -> str:
        return f"{self.owner}/{self.name}"

    @property
    def clone_url(self) -> str:
        return f"https://github.com/{self.full_name}.git"


def parse_repo_url(url: str) -> RepoRef:
    """Parse a github.com HTTPS or SSH repository URL into a RepoRef."""
    match = _REPO_URL_RE.match(url.strip())
    if match is None:
        raise GitHubError(f"Not a GitHub repository URL: {url!r}")
    owner, name = match["owner"], match["name"]
    name = name.removesuffix(".git")
    if not name or name in {".", ".."} or owner in {".", ".."}:
        raise GitHubError(f"Not a GitHub repository URL: {url!r}")
    return RepoRef(owner=owner, name=name)


class PullRequestInfo(BaseModel, frozen=True):
    number: int
    title: str
    state: str
    base_ref: str
    head_ref: str
    head_sha: str
    head_repo_full_name: str | None
    is_fork: bool
    html_url: str
    # Needed to push a fix to a fork PR's branch (allowed only if maintainer_can_modify).
    head_clone_url: str | None = None
    maintainer_can_modify: bool = False
    body: str = ""


_PR_HINT = "the token needs Pull requests: write"
# The footer every ci-fix PR description ends with (see ``ci_fix.report``).
CI_FIX_FOOTER = "Generated by ci-fix"
_ERROR_DATA_MAX = 500
_UNSET = object()


class PullRef(BaseModel, frozen=True):
    """A pull request opened or updated by ci-fix."""

    number: int
    html_url: str


class GitHubClient:
    """Small facade over PyGithub returning plain models."""

    def __init__(self, token: str | None = None, github: Github | None = None) -> None:
        if github is None:
            github = Github(auth=Auth.Token(token)) if token else Github()
        self._github = github
        self._login: object = _UNSET  # cached authenticated login (None = unknown)

    def authenticated_login(self) -> str | None:
        """Login of the token's user (cached); None when unavailable (e.g. app tokens)."""
        if self._login is _UNSET:
            try:
                self._login = self._github.get_user().login
            except Exception as exc:  # GithubException, or no auth at all
                log.debug("Could not determine the authenticated GitHub user: %s", exc)
                self._login = None
        login = self._login
        return login if isinstance(login, str) else None

    def get_pull_request(self, repo: RepoRef, number: int) -> PullRequestInfo:
        label = f"{repo.full_name}#{number}"
        log.debug("Fetching pull request %s", label)
        try:
            pr = self._github.get_repo(repo.full_name).get_pull(number)
            head_repo = pr.head.repo
            head_full_name = head_repo.full_name if head_repo is not None else None
            info = PullRequestInfo(
                number=pr.number,
                title=pr.title,
                state=pr.state,
                base_ref=pr.base.ref,
                head_ref=pr.head.ref,
                head_sha=pr.head.sha,
                head_repo_full_name=head_full_name,
                is_fork=head_full_name != pr.base.repo.full_name,
                html_url=pr.html_url,
                head_clone_url=head_repo.clone_url if head_repo is not None else None,
                maintainer_can_modify=pr.maintainer_can_modify is True,
                body=pr.body if isinstance(pr.body, str) else "",
            )
        except GithubException as exc:
            if exc.status == 404:
                raise GitHubError(f"Pull request {label} not found or not accessible") from exc
            raise GitHubError(
                f"GitHub API error fetching pull request {label} (HTTP {exc.status}): {exc.data}"
            ) from exc
        log.info(
            "PR %s %r: %s -> %s, state=%s, head=%s%s",
            label,
            info.title,
            info.head_ref,
            info.base_ref,
            info.state,
            info.head_sha[:12],
            f", fork={info.head_repo_full_name or '<deleted>'}" if info.is_fork else "",
        )
        return info

    # ------------------------------------------------------------------ delivery (slice 8)

    def _api_error(
        self, action: str, repo: RepoRef, exc: GithubException, hint: str
    ) -> GitHubError:
        data = str(exc.data)
        if len(data) > _ERROR_DATA_MAX:
            data = data[:_ERROR_DATA_MAX] + "…"
        msg = f"GitHub API error {action} on {repo.full_name} (HTTP {exc.status}): {data}"
        if exc.status in (403, 404, 422):
            msg += f"\nhint: {hint} on {repo.full_name}"
        return GitHubError(msg)

    def get_default_branch(self, repo: RepoRef) -> str:
        """The default branch of ``repo``."""
        try:
            return self._github.get_repo(repo.full_name).default_branch
        except GithubException as exc:
            raise self._api_error("reading the repository", repo, exc, _PR_HINT) from exc

    def _is_ours(self, body: str | None, author: str | None) -> bool:
        login = self.authenticated_login()
        return CI_FIX_FOOTER in (body or "") or (login is not None and author == login)

    def find_open_pr(self, repo: RepoRef, head: str, base: str) -> PullRef | None:
        """The open ci-fix PR in ``repo`` from ``head`` (``owner:branch``) into ``base``.

        A PR is ci-fix's when its body has the ci-fix footer or its author is the token's
        user. An open PR from that branch that is not ci-fix's raises ``GitHubError``.
        """
        log.debug("Looking for an open PR %s -> %s in %s", head, base, repo.full_name)
        try:
            pulls = self._github.get_repo(repo.full_name).get_pulls(
                state="open", head=head, base=base
            )
            for pr in pulls:
                author = pr.user.login if pr.user is not None else None
                if not self._is_ours(pr.body, author):
                    branch = head.split(":", 1)[-1]
                    raise GitHubError(
                        f"an open PR from {branch} already exists and was not created by "
                        f"ci-fix: {pr.html_url}"
                    )
                return PullRef(number=pr.number, html_url=pr.html_url)
        except GithubException as exc:
            raise self._api_error("listing pull requests", repo, exc, _PR_HINT) from exc
        return None

    def create_pull(self, repo: RepoRef, title: str, body: str, head: str, base: str) -> PullRef:
        """Open a PR in ``repo`` from branch ``head`` into ``base``."""
        log.debug("Creating PR %s -> %s in %s", head, base, repo.full_name)
        try:
            pr = self._github.get_repo(repo.full_name).create_pull(
                base=base, head=head, title=title, body=body
            )
        except GithubException as exc:
            raise self._api_error("creating a pull request", repo, exc, _PR_HINT) from exc
        return PullRef(number=pr.number, html_url=pr.html_url)

    def edit_pull(self, repo: RepoRef, number: int, title: str, body: str) -> PullRef:
        """Replace the title and description of PR ``number``."""
        log.debug("Updating PR %s#%d", repo.full_name, number)
        try:
            pr = self._github.get_repo(repo.full_name).get_pull(number)
            pr.edit(title=title, body=body)
        except GithubException as exc:
            raise self._api_error(f"updating pull request #{number}", repo, exc, _PR_HINT) from exc
        return PullRef(number=pr.number, html_url=pr.html_url)

    def find_comment(self, repo: RepoRef, number: int, marker: str) -> int | None:
        """Id of the first ci-fix comment on PR/issue ``number``.

        A comment matches when its body starts with ``marker`` and its author is the token's
        user; if that user cannot be determined (e.g. app tokens), the marker alone decides.
        """
        login = self.authenticated_login()
        try:
            issue = self._github.get_repo(repo.full_name).get_issue(number)
            for comment in issue.get_comments():
                if not (comment.body or "").startswith(marker):
                    continue
                author = comment.user.login if comment.user is not None else None
                if login is None or author == login:
                    return comment.id
        except GithubException as exc:
            raise self._api_error(f"reading comments of #{number}", repo, exc, _PR_HINT) from exc
        return None

    def create_comment(self, repo: RepoRef, number: int, body: str) -> str:
        """Comment on PR/issue ``number``; returns the comment URL."""
        try:
            issue = self._github.get_repo(repo.full_name).get_issue(number)
            return issue.create_comment(body).html_url
        except GithubException as exc:
            raise self._api_error(f"commenting on #{number}", repo, exc, _PR_HINT) from exc

    def edit_comment(self, repo: RepoRef, number: int, comment_id: int, body: str) -> str:
        """Replace the body of comment ``comment_id`` on PR/issue ``number``; returns its URL."""
        try:
            issue = self._github.get_repo(repo.full_name).get_issue(number)
            comment = issue.get_comment(comment_id)
            comment.edit(body)
            return comment.html_url
        except GithubException as exc:
            raise self._api_error(f"editing a comment on #{number}", repo, exc, _PR_HINT) from exc
